
steps:
- id: build
  name: gcr.io/cloud-builders/docker
  args: [
    'build', '-t', 'gcr.io/$PROJECT_ID/ros:latest',
    '--build-arg', 'GIT_SHA=$REVISION_ID',
    '--build-arg', 'UPLOAD_TO_SENTRY=true',
    '--build-arg', 'SENTRY_AUTH_TOKEN=$_SENTRY_AUTH_TOKEN',
    '.'
  ]

- id: tag
  name: gcr.io/cloud-builders/docker
  args: ['tag',
    'gcr.io/$PROJECT_ID/ros:latest',
    'gcr.io/$PROJECT_ID/ros:$REVISION_ID']

- id: push
  name: gcr.io/cloud-builders/docker
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    docker push gcr.io/$PROJECT_ID/ros:latest
    docker push gcr.io/$PROJECT_ID/ros:$REVISION_ID

# - id: deploy
#   name: 'danturner/manuel'
#   env: ['GH_TOKEN=$_GH_TOKEN']
#   entrypoint: '/bin/sh'
#   args:
#   - '-c'
#   - |
#     if [ "$BRANCH_NAME" == "master" ]; then
#       manuel \
#         --branch develop \
#         --value $REVISION_ID \
#         --message "Deploy ros $REVISION_ID"
#     fi